### ISSUE TITLE
Feedback for part 2

### ISSUE THREAD

**Issue by rlancaster96** [tamdbho/Demultiplex#2]
Hi Tam,
Great pseudocode, I could follow your logic easily the whole way through. I forgot to put counters in my own code, and you've reminded me I need to go back and add them. 
I'm not sure if we're allowed to use outside modules yet, but I've found the linecache module helpful when grabbing specific lines and could be useful for dealing with multiple files.
The only suggestion I have to slightly speed up your quality filtering would be that you don't strictly need the "OR" conditional in your first if statement - if either of those indexes have "N" they will not be in the index set anyway. So you probably don't have to look for "N", just go straight to comparing if they're in the index set.
Overall nice job and I learned some things from reading your code!

**Comment by tamdbho** [comment]
I'll definitely looking into linecache even if we can't use it in this project yet (need to confirm with Leslie), it'll still be super useful to know. It is true that setting another condition for identifying "N" is too redundant, thank you for pointing that out. I spread this knowledge forward because I also saw other people doing the same thing. I learned a lot from your review so thank you!
