### ISSUE TITLE
Pseudocode Review 

### ISSUE THREAD

**Issue by emybart415** [tamdbho/Demultiplex#3]
Line 4:
```
Create some line counting variable:
```
- I think this is going to be a very successful way of counting reads in each category! Im glad I keep seeing ways to do this in other peoples code because I forgot to do this in mine

Line 8:
```
Store all indexes from indexes.txt in a Store
```
- In a Store? Unsure what this is, maybe some sort of variable storage type I am not aware of 

Line 17:
```
call reverse_complement function for seq_line_R3
```
- Since you are reading all three files in parallel, and calling all line 2 variables "sequence" how will you make sure you only reverse compliment the R3 sequence 

The only other thing I can think of is you may have a hard time calling your reverse compliment function on any index with an N. Other than that your plan looks good! Short sweet and super easy to follow your logic

**Comment by tamdbho** [comment]
Line 8 was typo. Sorry for the confusion. 
I did not make it clear enough in the beginning but since I'm reading 4 files all at once, I will begin by making different variables for each components of each file. So for every round of my loop I will have a total of 16 variables. I'm debating if I should put each set of 4 variables (from each file) into a tuple before setting condition, that would make it easier to call on each file component. 
For my reverse complement function I'll utilize a dictionary and will be sure to include N as one of the key - value pair so that whenever it encounters an N in my string, it will still return an N. 
Thanks for the review, it definitely reinforced my plan for the official code.
